/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as ApiMadrasahRouteImport } from './routes/api/madrasah'
import { Route as appListRouteImport } from './routes/(app)/list'
import { Route as ApiCariIndexRouteImport } from './routes/api/cari/index'
import { Route as appDetailLokasi_idRouteImport } from './routes/(app)/detail/$lokasi_id'
import { Route as ApiDaftarId_lokasiId_sekolahRouteImport } from './routes/api/daftar/$id_lokasi.$id_sekolah'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiMadrasahRoute = ApiMadrasahRouteImport.update({
  id: '/api/madrasah',
  path: '/api/madrasah',
  getParentRoute: () => rootRouteImport,
} as any)
const appListRoute = appListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiCariIndexRoute = ApiCariIndexRouteImport.update({
  id: '/api/cari/',
  path: '/api/cari/',
  getParentRoute: () => rootRouteImport,
} as any)
const appDetailLokasi_idRoute = appDetailLokasi_idRouteImport.update({
  id: '/detail/$lokasi_id',
  path: '/detail/$lokasi_id',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiDaftarId_lokasiId_sekolahRoute =
  ApiDaftarId_lokasiId_sekolahRouteImport.update({
    id: '/api/daftar/$id_lokasi/$id_sekolah',
    path: '/api/daftar/$id_lokasi/$id_sekolah',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/list': typeof appListRoute
  '/api/madrasah': typeof ApiMadrasahRoute
  '/': typeof appIndexRoute
  '/detail/$lokasi_id': typeof appDetailLokasi_idRoute
  '/api/cari/': typeof ApiCariIndexRoute
  '/api/daftar/$id_lokasi/$id_sekolah': typeof ApiDaftarId_lokasiId_sekolahRoute
}
export interface FileRoutesByTo {
  '/list': typeof appListRoute
  '/api/madrasah': typeof ApiMadrasahRoute
  '/': typeof appIndexRoute
  '/detail/$lokasi_id': typeof appDetailLokasi_idRoute
  '/api/cari': typeof ApiCariIndexRoute
  '/api/daftar/$id_lokasi/$id_sekolah': typeof ApiDaftarId_lokasiId_sekolahRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/list': typeof appListRoute
  '/api/madrasah': typeof ApiMadrasahRoute
  '/(app)/': typeof appIndexRoute
  '/(app)/detail/$lokasi_id': typeof appDetailLokasi_idRoute
  '/api/cari/': typeof ApiCariIndexRoute
  '/api/daftar/$id_lokasi/$id_sekolah': typeof ApiDaftarId_lokasiId_sekolahRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/list'
    | '/api/madrasah'
    | '/'
    | '/detail/$lokasi_id'
    | '/api/cari/'
    | '/api/daftar/$id_lokasi/$id_sekolah'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/list'
    | '/api/madrasah'
    | '/'
    | '/detail/$lokasi_id'
    | '/api/cari'
    | '/api/daftar/$id_lokasi/$id_sekolah'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/list'
    | '/api/madrasah'
    | '/(app)/'
    | '/(app)/detail/$lokasi_id'
    | '/api/cari/'
    | '/api/daftar/$id_lokasi/$id_sekolah'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  ApiMadrasahRoute: typeof ApiMadrasahRoute
  ApiCariIndexRoute: typeof ApiCariIndexRoute
  ApiDaftarId_lokasiId_sekolahRoute: typeof ApiDaftarId_lokasiId_sekolahRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/madrasah': {
      id: '/api/madrasah'
      path: '/api/madrasah'
      fullPath: '/api/madrasah'
      preLoaderRoute: typeof ApiMadrasahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/list': {
      id: '/(app)/list'
      path: '/list'
      fullPath: '/list'
      preLoaderRoute: typeof appListRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/cari/': {
      id: '/api/cari/'
      path: '/api/cari'
      fullPath: '/api/cari/'
      preLoaderRoute: typeof ApiCariIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/detail/$lokasi_id': {
      id: '/(app)/detail/$lokasi_id'
      path: '/detail/$lokasi_id'
      fullPath: '/detail/$lokasi_id'
      preLoaderRoute: typeof appDetailLokasi_idRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/daftar/$id_lokasi/$id_sekolah': {
      id: '/api/daftar/$id_lokasi/$id_sekolah'
      path: '/api/daftar/$id_lokasi/$id_sekolah'
      fullPath: '/api/daftar/$id_lokasi/$id_sekolah'
      preLoaderRoute: typeof ApiDaftarId_lokasiId_sekolahRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appRouteRouteChildren {
  appListRoute: typeof appListRoute
  appIndexRoute: typeof appIndexRoute
  appDetailLokasi_idRoute: typeof appDetailLokasi_idRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appListRoute: appListRoute,
  appIndexRoute: appIndexRoute,
  appDetailLokasi_idRoute: appDetailLokasi_idRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  ApiMadrasahRoute: ApiMadrasahRoute,
  ApiCariIndexRoute: ApiCariIndexRoute,
  ApiDaftarId_lokasiId_sekolahRoute: ApiDaftarId_lokasiId_sekolahRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
